import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const onNext = (url) => {
      Router.push(url)
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}>
          <p>
            Get started&nbsp;
          </p>
        </div> */}

        <div className={styles.center}>
          <div
            className={styles.card}
            onClick={() => {onNext("/source/kafka")}}
          >
            <h2 className={inter.className}>
              Kafka
            </h2>
            <p className={inter.className}>
              Consume, process and serve multiple topics
            </p>
          </div>
          <div
              className={styles.card}
              onClick={() => {onNext("/source/postgres")}}
            >
              <h2 className={inter.className}>
                Postgres
              </h2>
              <p className={inter.className}>
                Replicate, process and serve one or more tables
              </p>
            </div>
        </div>

        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
